// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwtjjzryscwhqsgvvqzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3dGpqenJ5c2N3aHFzZ3Z2cXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzQ1MDEsImV4cCI6MjA2ODUxMDUwMX0.l5lgHxwSWVKkdJhuWqomKGz8Q35Ck2BCYIS2CJmPHZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});