// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuszlzbkzyayafbqavsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1c3psemJrenlheWFmYnFhdnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MTYwOTYsImV4cCI6MjA1MjM5MjA5Nn0.3Vhh36iek6V4PiPRa8aQTGSMdQGqPe7t6KzspMvp2-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);